import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { getFormByCode } from "../forms/catalog";
import type { CaseData } from "../types";

export async function generateFormPdf(
  formCode: string,
  answers: Record<string, string>,
  caseData: CaseData
): Promise<Uint8Array> {
  const form = getFormByCode(formCode);
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let page = pdfDoc.addPage([612, 792]);
  const { width, height } = page.getSize();
  let y = height - 50;

  const drawText = (text: string, size: number, bold = false) => {
    if (y < 60) {
      page = pdfDoc.addPage([612, 792]);
      y = height - 50;
    }
    page.drawText(text, {
      x: 50,
      y,
      size,
      font: bold ? boldFont : font,
      color: rgb(0.1, 0.1, 0.2),
      maxWidth: width - 100,
    });
    y -= size + 8;
  };

  drawText(form?.name ?? formCode, 16, true);
  drawText(`State: ${caseData.state} | County: ${caseData.county}`, 10);
  drawText("—".repeat(60), 10);
  y -= 8;

  if (form) {
    for (const field of form.fields) {
      const value = answers[field.key] ?? "";
      drawText(`${field.label}:`, 10, true);
      drawText(value || "(not provided)", 11);
      y -= 4;
    }
  }

  drawText("—".repeat(60), 10);
  drawText("Generated by Divorce Filing Assistant (prototype)", 8);
  drawText("Not an official court form — for demonstration only", 8);

  return pdfDoc.save();
}

export async function generatePacket(
  caseData: CaseData,
  formCodes: string[]
): Promise<{ filename: string; data: Uint8Array }[]> {
  const results: { filename: string; data: Uint8Array }[] = [];

  for (const code of formCodes) {
    const answers = caseData.formAnswers[code] ?? {};
    const data = await generateFormPdf(code, answers, caseData);
    results.push({ filename: `${code}.pdf`, data });
  }

  return results;
}

export async function downloadAllForms(
  caseData: CaseData,
  formCodes: string[]
): Promise<void> {
  const packets = await generatePacket(caseData, formCodes);

  for (const { filename, data } of packets) {
    const blob = new Blob([new Uint8Array(data)], { type: "application/pdf" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    await new Promise((r) => setTimeout(r, 300));
  }
}

export async function downloadCombinedPacket(
  caseData: CaseData,
  formCodes: string[]
): Promise<void> {
  const merged = await PDFDocument.create();
  const packets = await generatePacket(caseData, formCodes);

  for (const { data } of packets) {
    const doc = await PDFDocument.load(data);
    const pages = await merged.copyPages(doc, doc.getPageIndices());
    pages.forEach((p) => merged.addPage(p));
  }

  const bytes = await merged.save();
  const blob = new Blob([new Uint8Array(bytes)], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `divorce-filing-packet-${caseData.county}-${Date.now()}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}
